title: Karim ZN
description: Software Engineer & ML Specialist
baseurl: ""
url: "https://karimzn00.github.io/portfolio"
github_username: karimzn00
theme: jekyll-theme-minimal

plugins:
  - jekyll-feed
  - jekyll-seo-tag
